Repository quarkiverse/quarkus-artemis, pull requests merged in 2023-02, with the labels that each got.

#152 #151: updated artemis image from 1.0.9 to 1.0.15
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
Labels: maintenance

#153 Improve pipeline
  .github/workflows/build.yml
  pom.xml
Labels: enhancement

#159 POM cleanup
  pom.xml
Labels: maintenance

#149 Fix #148 to use ConnectionFactoryWrapperItem
  build-parent/pom.xml
  docs/modules/ROOT/pages/includes/attributes.adoc
  jms/deployment/pom.xml
  jms/deployment/src/main/java/io/quarkus/artemis/jms/deployment/ArtemisJmsProcessor.java
  jms/deployment/src/main/java/io/quarkus/artemis/jms/deployment/ArtemisJmsWrapperBuildItem.java
  jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/ArtemisJmsRecorder.java
  jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/ArtemisJmsWrapper.java
Labels: maintenance

#161 replaced anonymous classes with lambdas
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisCoreRecorder.java
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/health/ArtemisHealthSupportRecorder.java
  docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
  jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/ArtemisJmsRecorder.java
Labels: maintenance

#163 #157: dependabot configuration for branch 2.x
  .github/dependabot.yml
Labels: maintenance

#169 added cancel-steps to all jobs to fail the pipeline fast
  .github/workflows/build.yml
Labels: maintenance

#170 native and JVM tests now run in parallel
  .github/workflows/build.yml
Labels: maintenance

#171 better pr decoration
  .github/workflows/build.yml
Labels: maintenance

#173 Release 2.1.0
  .github/project.yml
Labels: release

#174 Use publish-report action
  .github/workflows/build.yml
Labels: maintenance

#175 Upgraded publish-report action from v1.0.0 to v1.0.1
  .github/workflows/build.yml
Labels: maintenance
