Repository quarkiverse/quarkus-artemis, pull requests merged in 2023-03, with the labels that each got.

#182 Remove io.quarkus:quarkus-jms-spi-deployment in build-parent
  build-parent/pom.xml
Labels: maintenance

#183 Release 3.0.0.Alpha7
  .github/project.yml
Labels: release

#186 #184: use ReflectiveCallBuildItem builder
  core/deployment/src/main/java/io/quarkus/artemis/core/deployment/ArtemisCoreProcessor.java
Labels: maintenance

#185 #156: remove package-phase from populate-cache-job
  .github/workflows/build.yml
Labels: maintenance, quarkus-3

#193 Release 3.0.0.CR1
  .github/project.yml
Labels: release
