Repository quarkiverse/quarkus-artemis, pull requests merged in 2023-06, with the labels that each got.

#231 #230: Initialize ConnectionFactory at application startup
  .github/workflows/build.yml
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisCoreRecorder.java
  docs/modules/ROOT/pages/includes/attributes.adoc
  jms/deployment/src/main/java/io/quarkus/artemis/jms/deployment/ArtemisJmsProcessor.java
  jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/ArtemisJmsRecorder.java
Labels: bug, backport/2.x

#233 Release 3.0.1
  .github/project.yml
Labels: release

#234 Release 2.1.1
  .github/project.yml
Labels: release

#238 Update quay.io/artemiscloud/activemq-artemis-broker from 1.0.14 to 1.0.18
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
  docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
Labels: maintenance

#239 documentation: important notice about build-time config
  docs/modules/ROOT/pages/index.adoc
Labels: docs, backport/2.x
