Repository quarkiverse/quarkus-artemis, pull requests merged in 2024-07, with the labels that each got.

#554 Release 3.0.7
  .github/project.yml
Labels: release

#555 Release 3.1.6
  .github/project.yml
Labels: release

#560 Maintenance
  core/deployment/src/main/java/io/quarkus/artemis/core/deployment/DevServicesArtemisProcessor.java
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisUtil.java
  integration-tests/ra/src/main/java/io/quarkus/it/artemis/ra/JcaResource.java
  integration-tests/ra/src/main/java/io/quarkus/it/artemis/ra/MyQueueMessageEndpoint.java
  integration-tests/ra/src/main/java/io/quarkus/it/artemis/ra/SalesEndpoint.java
  integration-tests/ra/src/test/java/io/quarkus/it/artemis/ra/InjectionTest.java
  integration-tests/ra/src/test/java/io/quarkus/it/artemis/ra/IronJacamarConfigTest.java
  integration-tests/ra/src/test/java/io/quarkus/it/artemis/ra/JcaResourceIT.java
  integration-tests/ra/src/test/java/io/quarkus/it/artemis/ra/JcaResourceTest.java
  integration-tests/ra/src/test/java/io/quarkus/it/artemis/ra/MetricsTest.java
  integration-tests/ra/src/test/java/io/quarkus/it/artemis/ra/TransactionTest.java
  jms/runtime/src/main/java/io/quarkus/artemis/jms/runtime/ArtemisJmsRecorder.java
Labels: maintenance, backport-3.2.x

#561 Upgrade default artemis image
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
Labels: maintenance

#564 Strike-through versions that have reached their end of life.
  docs/modules/ROOT/pages/quarkus-artemis-jms.adoc
Labels: docs

#565 Reorder EOL Tables: newest version to oldest version
  docs/modules/ROOT/pages/quarkus-artemis-jms.adoc
Labels: docs, backport-3.2.x

#573 Upgrade maven
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: maintenance, backport-3.2.x

#572 Repeat `NettyConnectorFactory` for each host
  ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java
Labels: bug, backport-3.2.x

#579 Upgrade default artemis image quay.io/artemiscloud/activemq-artemis-b…
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
  docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
Labels: dependencies
