Repository quarkiverse/quarkus-artemis, pull requests merged in 2024-10, with the labels that each got.

#641 Fix NullPointerException due to missing schema
  core/deployment/src/main/java/io/quarkus/artemis/core/deployment/DevServicesArtemisProcessor.java
Labels: backport-3.2.x

#655 Release 3.2.5
  .github/project.yml
Labels: release

#660 Bump artemis image
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
  docs/modules/ROOT/pages/includes/attributes.adoc
  docs/modules/ROOT/pages/includes/quarkus-artemis-core.adoc
  docs/modules/ROOT/pages/includes/quarkus-artemis-core_quarkus.artemis.adoc
Labels: maintenance
