Repository quarkiverse/quarkus-artemis, pull requests merged in 2024-03, with the labels that each got.

#401 support additional activation specs in the config
  ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/ArtemisResourceAdapterFactory.java
Labels: enhancement

#438 Add branch 3.2.x to build.yml and dependabot.yml
  .github/dependabot.yml
  .github/workflows/build.yml
Labels: maintenance, backport/2.x, backport/3.0.x, backport/3.1.x, backport-3.2.x

#435 Release 3.0.6
  .github/project.yml
Labels: release

#436 Release 3.1.5
  .github/project.yml
Labels: release

#439 Set antora version to 3.2.x
  docs/antora.yml
Labels: docs

#440 Upgrade camel-quarkus.platform.version and quarkus.version from 3.8.2 to 3.9.0.CR1
  pom.xml
Labels: dependencies

#451 Release 3.3.0.CR2
  .github/project.yml
Labels: release

#460 Fixate artemis minor version on branches with LTS support
  .github/dependabot.yml
Labels: maintenance, backport/2.x, backport/3.0.x, backport/3.1.x, backport-3.2.x

#461 Fix dependabot config
  .github/dependabot.yml
Labels: maintenance, backport/2.x, backport/3.0.x, backport/3.1.x, backport-3.2.x

#414 Update actions
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: maintenance

#462 The version for radcortez/project-metadata-action should be main
  .github/workflows/release.yml
Labels: maintenance, backport/2.x, backport/3.0.x, backport/3.1.x, backport-3.2.x
