Repository quarkiverse/quarkus-artemis, pull requests merged in 2025-07, with the labels that each got.

#829 Support Compose DevService
  docs/modules/ROOT/pages/quarkus-artemis-ra.adoc
  ra/deployment/src/main/java/io/quarkus/artemis/jms/ra/deployment/DevServicesArtemisProcessor.java
Labels: enhancement

#856 Release 3.8.3
  .github/project.yml
Labels: release

#865 Update quay.io/arkmq-org/activemq-artemis-broker
  core/runtime/src/main/java/io/quarkus/artemis/core/runtime/ArtemisDevServicesBuildTimeConfig.java
  ra/runtime/src/main/java/io/quarkus/artemis/jms/ra/runtime/ArtemisDevServicesBuildTimeConfig.java
Labels: maintenance

#869 Release 3.8.4
  .github/project.yml
Labels: release
